CREATE DATABASE milliomos;

CREATE TABLE user (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  password VARCHAR(25) NOT NULL,
  email VARCHAR(25) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE question (
  id INT NOT NULL AUTO_INCREMENT,
  question VARCHAR(100) NOT NULL,
  right VARCHAR(50) NOT NULL,
  wrong1 VARCHAR(50) NOT NULL,
  wrong2 VARCHAR(50) NOT NULL,
  wrong3 VARCHAR(50) NOT NULL,
  level TINYINT(1) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE score (
  id INT NOT NULL AUTO_INCREMENT,
  userid INT NOT NULL FOREIGN KEY REFERENCES user(id) ON DELETE CASCADE, 
  money INT DEFAULT 0,
  score INT DEFAULT 0,
  PRIMARY KEY (id)
);
